export const documentosCopy = {
  pageTitle: "Documentos",
  pageDescription: "Todos os documentos recebidos em um só lugar.",
  inboxTitle: "Caixa de entrada",
  enviarTitle: "Enviar documentos",
  pendentesTitle: "Precisa da sua atenção",
  detalheTitle: "Detalhe do documento",
  dropzoneHint: "Arraste arquivos ou uma pasta aqui — XML, PDF, ZIP e outros formatos aceitos.",
  dropzoneSupport: "Notas fiscais, boletos, extratos e documentos de transporte no mesmo lugar.",
  homeDropzoneLabel: "Arraste arquivos aqui",
  homeDropzoneHint: "ou clique para escolher — notas, extratos, boletos e transporte",
  chaveColumn: "Identificador",
  numeroColumn: "Número",
  titulosSection: "Documentos de transporte",
  emptyTitle: "Nenhum documento ainda",
  emptyDescription: "Envie arquivos para começar.",
  processSuccess: (ok: number, total: number) =>
    `${ok} documento(s) processado(s) de ${total} arquivo(s)`,
  pendentesLink: (count: number) => `${count} entrega(s) aguardando confirmação`,
  tabs: {
    todos: "Todos",
    pendentes: "Pendentes",
    erro: "Com erro",
  },
  filters: {
    all: "Todos os tipos",
    nota: "Nota",
    boleto: "Boleto",
    extrato: "Extrato",
    transporte: "Transporte",
    outros: "Outros",
  },
  timeline: {
    recebido: "Documento recebido",
    processado: "Leitura automática",
    relacionado: "Relacionamentos",
    confirmado: "Confirmado",
  },
} as const;
